# Generated by Django 4.2.4 on 2023-09-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_detail_spider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
